[package]
name = "compression_test"
version = "0.1.0"
authors = ["Tobias Laving <tobias.laving@ericsson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smaz = "0.1.0"
lz4_flex = "0.7.5"